modLoader="javafml"
loaderVersion="[47,)"
license="MIT (CC BY-NC-SA 4.0 for some Assets)"
issueTrackerURL="https://github.com/quiqueck/BetterEnd/issues"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
description="More content for The End dimension, including new biomes, plants, mobs, mechanics, terrain generation and more."
authors="Quiqueck, paulevs (original author), Bulldog83, Edos, Yuki, Seaward, Firel"
displayURL="https://www.curseforge.com/minecraft/mc-mods/betterend"
logoFile="assets/betterend/icon.png"

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="[${forge_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="[${minecraft_version}]"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="bclib"
mandatory=true
versionRange="[${bclib_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="emi"
mandatory=false
versionRange="[1.0,)"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="patchouli"
mandatory=false
versionRange="[${patchouli_version},)"
ordering="NONE"
side="CLIENT"

[[mixins]]
config="betterend.mixins.common.json"

[[mixins]]
config="betterend.mixins.client.json"
